In [1]:
# Install the necessary libraries
!pip install pandas
!pip install openpyxl

In [1]:
# Import the necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
# Read the xlsx files
text_summary_data = pd.read_excel('text_summary_datasets_v2.xlsx')
training_data = pd.read_excel('training_data_v2.xlsx')

In [3]:
# Displaying the first few rows of the training data
training_data.head()

Index  Category     dim_1     dim_2     dim_3     dim_4     dim_5  \
0      0         0 -0.882278 -0.647234  0.050173 -0.448188 -0.175582   
1      1         0 -0.702665 -0.462591  0.162085 -0.029182 -0.280842   
2      2         0 -0.327257 -0.397209  0.035037 -0.064671 -0.435734   
3      3         0 -0.793734 -0.470964 -0.278644 -0.292047 -0.565868   
4      4         0 -0.272840 -0.556684  0.001737 -0.229906 -0.495732   

      dim_6     dim_7     dim_8  ...   dim_759   dim_760   dim_761   dim_762  \
0  0.125284 -0.335781 -0.396106  ...  0.568470 -0.326577  0.026089 -0.407658   
1  0.047459  0.109864 -0.540210  ...  0.249440 -0.422917  0.033820 -0.226271   
2  0.535525  0.134867 -0.213102  ...  0.710835 -0.191510 -0.068998 -0.262279   
3  0.546791  0.604674 -0.069190  ...  0.387789 -0.596448 -0.291108 -0.320205   
4  0.176596 -0.141926 -0.352247  ...  0.660122 -0.534026  0.347033 -0.279629   

    dim_763   dim_764   dim_765   dim_766   dim_767   dim_768  
0 -0.162295 -0.121949 -0.386429  0.135763  0.516049  0.731324  
1 -0.324386 -0.036914 -0.588373 -0.344278  0.329853  0.195897  
2 -0.214397  0.095195 -0.503536  0.142249  0.206015  0.182094  
3 -0.362207  0.179917 -0.600026 -0.200465  0.776508 -0.155819  
4 -0.397189  0.226515 -0.547098  0.431136  0.102714  0.422797  

[5 rows x 770 columns]

In [4]:
# Splitting the dataset into features (X) and target (y)
x = training_data.drop(columns=["Index","Category"])
y = training_data["Category"]

In [21]:
# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [6]:
## Random Forest Classifier
# Initializing the Random Forest classifier
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Training the model
rf_clf.fit(X_train, y_train)

# Making predictions
rf_y_pred = rf_clf.predict(X_test)

# Evaluating the model
rf_accuracy = accuracy_score(y_test, rf_y_pred)
rf_conf_matrix = confusion_matrix(y_test, rf_y_pred)
rf_class_report = classification_report(y_test, rf_y_pred)

print("Random Forest Classifier")
print(f"Accuracy: {rf_accuracy}")
print("Confusion Matrix:")
print(rf_conf_matrix)
print("Classification Report:")
print(rf_class_report)

Random Forest Classifier
Accuracy: 0.9
Confusion Matrix:
[[11  0  0  0]
 [ 1 17  2  0]
 [ 0  1 14  0]
 [ 0  2  0 12]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        11
           1       0.85      0.85      0.85        20
           2       0.88      0.93      0.90        15
           3       1.00      0.86      0.92        14

    accuracy                           0.90        60
   macro avg       0.91      0.91      0.91        60
weighted avg       0.90      0.90      0.90        60



In [7]:
## Support Vector Machine Classifier
# Initializing the SVM classifier
svm_clf = SVC(kernel='linear', random_state=42)

# Training the model
svm_clf.fit(X_train, y_train)

# Making predictions
svm_y_pred = svm_clf.predict(X_test)

# Evaluating the model
svm_accuracy = accuracy_score(y_test, svm_y_pred)
svm_conf_matrix = confusion_matrix(y_test, svm_y_pred)
svm_class_report = classification_report(y_test, svm_y_pred)

print("\nSupport Vector Machine Classifier")
print(f"Accuracy: {svm_accuracy}")
print("Confusion Matrix:")
print(svm_conf_matrix)
print("Classification Report:")
print(svm_class_report)


Support Vector Machine Classifier
Accuracy: 0.9833333333333333
Confusion Matrix:
[[11  0  0  0]
 [ 1 19  0  0]
 [ 0  0 15  0]
 [ 0  0  0 14]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        11
           1       1.00      0.95      0.97        20
           2       1.00      1.00      1.00        15
           3       1.00      1.00      1.00        14

    accuracy                           0.98        60
   macro avg       0.98      0.99      0.98        60
weighted avg       0.98      0.98      0.98        60



In [10]:
# import required libs
import pandas as pd
from transformers import BertTokenizer, BertModel
import re

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
import torch

D:\anaconda3\envs\huggingman\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
D:\anaconda3\envs\huggingman\Lib\site-packages\transformers\utils\generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(


In [11]:
# tokenizer and bert
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
bert_model = BertModel.from_pretrained("bert-base-uncased")

D:\anaconda3\envs\huggingman\Lib\site-packages\huggingface_hub-0.23.3-py3.8.egg\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.


In [13]:
# nltk libs
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [14]:
# text pre-processing function
def preprocess_text(text):
    # case standardization
    text = text.lower() # dont care about capitalization yet
    
    # puntuation removal
    text = text.replace('"', '') # our text consists of multiple sentences, some punctuations are needed

    # tokenized text
    tokens = tokenizer.tokenize(text)
    
    # stop word removal
    # new_tokens = []
    # for token in tokens:
    #    if token.lower() not in stop_words:
    #        new_tokens.append(token)
    '''
    original:
    ['the', 'diagnosis', 'of', 'v', '##kh', 'followed', 'revised', 'diagnostic', 'criteria', 'by', 'the', 'internation', ...]
    remove stop words:
    ['diagnosis', 'v', '##kh', 'followed', 'revised', 'diagnostic', 'criteria', 'international', ...]
    Thus don't remove stop words, it might lead to poor BERT semantic understand. 
    '''

    # lemmatizer and stemmer
    # Lemmatization and Stemming
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]

    # stemmed_tokens = [stemmer.stem(token) for token in tokens]

    # print(tokens)
    # print(lemmatized_tokens)
    # print(stemmed_tokens)
    '''
    lemmatized:
    ['the', 'diagnosis', 'of', 'v', '##kh', 'followed', 'revised', 'diagnostic', 'criterion', 'by', 'the', 'international', ...]
    stemmed:
    ['the', 'diagnosi', 'of', 'v', '##kh', 'follow', 'revis', 'diagnost', 'criteria', 'by', 'the', 'intern', ...]
    Stemmed is bad here, choose lemmatizer over stemmer.
    '''

    # change tokens back to senteces
    def detokenize(tokens):
        new_tokens = []
        for token in tokens:
            if token.startswith("##"):
                new_tokens[-1] += token[2:]
            else:
                new_tokens.append(token)
        text = " ".join(new_tokens)
        text = re.sub(r'\s([?.!,\'-](?:\s|$))', r'\1', text)
        return text

    text = detokenize(lemmatized_tokens)

    # capitalize first alphabet of each sentence
    text = re.sub(r"(^|[.!?]\s+)(\w+)", lambda match: match.group(1) + match.group(2).capitalize(), text)

    return text

In [15]:
# BERT
'''
choose BERT to get text semantic meaning to be used for classification and clustering. This is more advanced than keywords counting.
'''
def toBert(text):
    inputs = tokenizer(text, return_tensors="pt", max_length=512, truncation=True, padding="max_length")
    outputs = bert_model(input_ids=inputs["input_ids"], attention_mask=inputs["attention_mask"])
    return outputs.last_hidden_state[0, 0, :]

In [12]:
# Upload Real Case Dataset


In [87]:
new_paragraph = "Seven out of 12 patients no longer needed daily insulin shots after receiving a full dose of the gene therapy, dubbed VX-800, researchers reported Friday at the American Diabetes Association annual meeting in Orlando, FL. Another two needed about 70% less insulin daily to keep their blood sugar stable, results show. This positive data adds to the growing body of evidence for VX-880 potential to revolutionize the treatment of type 1 diabetes, said researcher Dr. Piotr Witkowski, director of the pancreatic and islet transplant program at the University of Chicago. People with type 1 diabetes arent able to produce enough insulin to keep blood sugar levels stable. Type 1 diabetes occurs when the immune system mistakenly targets and attacks the islet cells in the pancreas that generate insulin."

In [48]:
new_paragraph = "The film is brief and its AI origins are only really obvious when it is paused. Otherwise, you might think it was simply the victim of an overly enthusiastic editor with access to some powerful visual effects software and actors who don't know how to perform in front of a green screen. Overall, it manages to mostly avoid the uncanny valley except for when the young founder smiles, then it a little too much like watching The Polar Express. Still, when considering it was produced with the alpha version of Sora and with relatively limited time and resources, you can see why some are very excited about Sora. Through Sora, we were able to tell this incredible story with remarkable speed and efficiency, Native Foreign Chief Creative Officer and the film's director Nik Kleverov said in a statement.  Toys R Us is the perfect brand to embrace this AI-forward strategy, and we are thrilled to collaborate with their creative team to help lead the next wave of innovative storytelling."

In [100]:
new_paragraph = "ou might be familiar with spreadsheets or databases. A blockchain is somewhat similar because it is a database where information is entered and stored. But the key difference between a traditional database or spreadsheet and a blockchain is how the data is structured and accessed. A blockchain consists of programs called scripts that conduct the tasks you usually would in a database: Entering and accessing information and saving and storing it somewhere. A blockchain is distributed, which means multiple copies are saved on many machines, and they must all match for it to be valid."

In [113]:
new_paragraph = "Programmable networking protocols, such as OpenFlow, direct traffic among network devices in an SDN network. The Open Networking Foundation (ONF) helped to standardize the OpenFlow protocol and other open source SDN technologies. By combining these components, organizations get a simpler, centralized way to manage networks. SDN strips away the routing and packet forwarding functions, known as the control plane, from the data plane or underlying infrastructure. SDN then implements controllers, considered the brain of the SDN network, and layers them above the network hardware in the cloud or on-premises. This lets teams use policy-based management—a kind of automation—to manage network control directly. SDN controllers tell switches where to send packets. In some cases, virtual switches embedded in software or hardware replace the physical switches. This consolidates their functions into a single, intelligent switch that can check data packets and their virtual machine destinations to ensure there are no issues before moving packets along."

In [114]:
text = preprocess_text(new_paragraph)

In [115]:
outputs = toBert(text)

In [116]:
outputs.shape

torch.Size([768])

In [117]:
outputs = outputs.detach().numpy()

In [118]:
outputs = np.expand_dims(outputs, axis=0)

In [119]:
outputs.shape

(1, 768)

In [120]:
columns = [f'dim_{i}' for i in range(1, 769)]

In [121]:
df = pd.DataFrame(outputs, columns=columns)

In [122]:
df.shape

(1, 768)

In [123]:
type(df)

pandas.core.frame.DataFrame

In [124]:
# Making predictions
svm_y_pred = svm_clf.predict(df)

In [125]:
svm_y_pred

array([2], dtype=int64)

In [38]:
# Making predictions
svm_y_pred = svm_clf.predict(X_test)

D:\anaconda3\envs\huggingman\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [41]:
X_test

dim_1     dim_2     dim_3     dim_4     dim_5     dim_6     dim_7  \
95  -0.371783 -0.085010 -0.433551 -0.211489 -0.408652 -0.202125 -0.008467   
15  -0.885291 -0.909994  0.433861 -0.002347 -0.395468  0.216916 -0.446348   
30  -0.530586 -0.119905 -0.451796 -0.104974 -0.374829 -0.344402  0.482314   
158 -0.329005 -0.147420  0.434372  0.019946 -0.105901 -0.294890 -0.160020   
128 -0.239914 -0.098280  0.084705  0.337961 -0.399834 -0.465882  0.228993   
115 -0.576521 -0.189101  0.202255 -0.000682 -0.078973 -0.169888  0.302044   
69  -0.321925 -0.363460 -0.358947  0.098452 -0.533830  0.247866  0.045391   
170 -0.336527  0.025666  0.104494 -0.044850 -0.485510 -0.216635  0.424055   
174 -0.183418 -0.278766 -0.088772 -0.057157 -0.578566  0.220462  0.247467   
45   0.076175 -0.680333  0.340795 -0.245307  0.007886  0.420016  0.127318   
66  -0.337251 -0.246626 -0.380882 -0.148214 -0.468540 -0.339641  0.191095   
182 -0.784760 -0.161321  0.065486  0.108402 -0.613932 -0.064227  0.217114   
165 -0.239056 -0.234293  0.005209  0.038160 -0.348068 -0.192169  0.007791   
78  -0.536338 -0.326760  0.163209 -0.190317 -0.464626 -0.302876  0.126689   
186 -0.494364 -0.252288 -0.025417 -0.021686 -0.293787 -0.475408  0.326396   
177 -0.705727 -0.411105  0.331786  0.253031 -0.404797 -0.558422  0.124931   
56  -0.584605  0.167971 -0.257208 -0.547727 -0.273502  0.097984 -0.001701   
152 -0.675094 -0.033365  0.072944  0.240776 -0.015596 -0.500234 -0.043850   
82  -0.218815  0.090943  0.113025  0.005733 -0.454013  0.055382  0.416984   
68  -0.527661 -0.098195 -0.325204 -0.111123 -0.339674 -0.095482 -0.018245   
124 -0.498822 -0.050895  0.398012 -0.021844 -0.132585 -0.285026  0.271003   
16  -0.914009 -0.697398  0.266523 -0.158200 -0.360783  0.166987 -0.256124   
148 -0.537877  0.153264  0.678816 -0.011105  0.044487 -0.448745  0.092393   
93  -0.742483 -0.007253  0.024638 -0.137929 -0.213876 -0.143542 -0.029706   
65  -0.310374 -0.183500 -0.307875 -0.002385 -0.609950 -0.101611  0.211293   
60  -0.618327 -0.470406  0.029095 -0.135543 -0.198810 -0.031091  0.004043   
84  -0.935507 -0.388074 -0.908712 -0.065093 -0.924105  0.271741  0.342711   
67  -0.213723  0.005310 -0.543033  0.566412 -0.410138 -0.112418  0.243455   
125 -0.491231 -0.200957  0.222590  0.025429  0.010329 -0.572154 -0.000334   
132 -0.684550 -0.112930  0.562851  0.094268  0.129935 -0.640057  0.007807   
9   -0.801591 -0.317120 -0.208542 -0.209656 -0.162129 -0.013105  0.020604   
18  -0.860120 -1.001416 -0.227275 -0.237653 -0.212726  0.410007  0.298585   
55  -0.356178  0.269668 -0.520146 -0.401096 -0.030700 -0.108232  0.124364   
75  -0.474063 -0.124464 -0.640560 -0.390995 -0.200768  0.033975  0.359575   
150 -0.487098 -0.152027  0.212723  0.264519 -0.269152 -0.579545 -0.157814   
104 -0.636107 -0.013931  0.232908 -0.181511  0.139434 -0.535017  0.191426   
135 -0.749336 -0.385758  0.293022 -0.112205 -0.092222 -0.584759 -0.352975   
137 -0.470525 -0.643098  0.171782 -0.225376 -0.230356 -0.283547 -0.308445   
164 -0.736931 -0.259714  0.134387  0.377613 -0.452256 -0.659564 -0.107536   
76  -0.298346  0.154283 -0.213561 -0.380092 -0.353891  0.281502  0.321101   
79  -0.634685 -0.214064 -0.044035  0.060735 -0.489498 -0.238624  0.390657   
197 -0.690654 -0.019106  0.046442 -0.335516 -0.110747 -0.162075  0.434238   
38  -0.198987 -0.470553 -0.269534  0.018469  0.022434  0.081469 -0.243688   
24  -0.620166 -0.804895  0.079065 -0.291408 -0.303426  0.443928  0.281493   
122 -0.668348  0.119644 -0.086117 -0.134196  0.035448 -0.174107  0.198113   
195 -0.619001 -0.416961  0.195633 -0.165133 -0.219509 -0.356662 -0.093528   
29  -0.447944  0.025192 -0.475626  0.181468 -0.686970  0.089939  0.547490   
19  -0.823657 -0.683853 -0.431248 -0.273684 -0.315633  0.410881  0.087880   
143 -0.484142 -0.453440  0.383631 -0.116491 -0.361298 -0.524967  0.080555   
86  -0.643438 -0.192957  0.477628 -0.208608 -0.414423 -0.310376  0.351909   
114 -1.014240  0.089502  0.125237  0.120746 -0.079000 -0.277069 -0.244749   
173 